### PR TITLE
Upgrade to assertj-core 3.11.1

### LINKED ISSUE #13: NoSuchMethodError with AssertJ >= 3.11.0
After updating to assertj-core 3.11.1 I've started seeing:

```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/lang/String;)Lorg/assertj/core/api/AbstractCharSequenceAssert;

	at com.revinate.assertj.json.JsonPathAssert.jsonPathAsString(JsonPathAssert.java:32)
```
when running my tests.

This seems to have been caused by a signature changes in the fix for joel-costigliola/assertj-core#1269, in particular the change to Assertions.java:

```diff
-  public static AbstractCharSequenceAssert<?, String> assertThat(String actual) {
+  public static AbstractStringAssert<?> assertThat(String actual) {
```

I think it's sufficient to just bump the assertj-core dependency to 3.11.1 to fix this, though probably `jsonPathAsString` should return an `AbstractStringAssert<?>` rather than `AbstractCharSequenceAssert<?, String>` to pick up the additional methods that were added in that assertj-core change.

### PR DESCRIPTION
**Pull request by ljrmorgan**
Bump to assertj-core 3.11.1 to resolve `NoSuchMethodError`s after a signature changes in assertj-core.

Fixes #13

### CODE REVIEW

**Comment by ljrmorgan** [comment]
The build failure doesn't seem related to the change, doesn't look like it's got as far as compiling anything.

@jrglee Are you happy with the approach that I've taken here? One downside is that this will not work with versions of assertj < 3.11, I could maybe use reflection to work around that but thought it would be best to keep it simple.

**Comment by bschelberg** [comment]
Seems like this project is dead, this one worked for me: https://github.com/lukas-krecan/JsonUnit. As recommended by Joel Costigliola: https://stackoverflow.com/a/47625667/1303158

**Comment by wimdeblauwe** [comment]
Would be good if somebody could put that in the readme to avoid waisting time on this project.

**Comment by jrglee** [comment]
Hello, I no longer work at Revinate since 2019. And I am not a maintainer of this project anymore, nor I have permissions to push any change.

It does look like this library is dead. I recommend you to migrate to an existing one with up-to-date dependencies and more advanced features. Or simplify fork it and keep it up-to-date.

To give some additional context. This library was created back in 2015, from a collection of test utilities that we end up copying between multiple repos. We did not have a good Artifactory deployment, and we thought it was a nice idea to open source it to get hosting and CI for free while giving us an opportunity to be exposed to different tools.

Cheers!
